jobs:
    include:
      -
        name: Ubuntu 18.04
        dist: bionic
        language: python
        python:
          - "3.6"
        cache:
          directories:
            - "~/.platformio"
        install:
          - pip install -U platformio
          - platformio update
        script:
          # Test builds status
          - platformio run -v -e hardware_usb
          # Run tests
          - platformio test -e test_native
      -
        name: macOS 10.14
        os: osx
        osx_image: xcode11.3
        language: shell
        cache:
          directories:
            - "~/.platformio"
        install:
          - pip install -U platformio
          - platformio update
        script:
          # Test builds status
          - platformio run -e hardware_usb
      -
        name: Windows
        os: windows           # Windows 10.0.17134 N/A Build 17134
        language: shell
        before_install:
          - choco install python --version 3.6.8
          - python -m pip install --upgrade pip
        env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
        install:
          - pip install -U platformio
          - platformio update
        script:
          # Test builds status
          #- python -c "import os; print(' '.join(['-I {}'.format(i[0]) for i in os.walk(os.path.abspath('hal/stm32f072cb'))]))"
          #- python -c "import os; print(' '.join(['-I{}'.format(i[0]) for i in os.walk(os.path.join('hal', 'stm32f072cb'))]))"
          #- python -c "import os; print(' '.join(['-I {}'.format(os.posixpath.normpath(i[0])) for i in os.walk('hal/stm32f072cb')]))"
          #- python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\\','/')) for i in os.walk('hal/stm32f072cb')]))"
          - platformio run -v -e hardware_usb
